/* ============================================================
   deck.js — oyun içerikleri (tek kaynak).
   Hem tarayıcı hem sunucu bu dosyayı kullanır.

   Ben Hiç… seviyeleri:
     'klasik' → masada kim olursa olsun rahat sorulur
     'aci'    → yakın arkadaş grubu; ilişkiler, itiraflar, cinsellik
   ============================================================ */

export const NHIE = [
/* ------------------------------------------------------------------
   KLASİK — 100
------------------------------------------------------------------ */
{ s:'klasik', t:'Hiç uçağa binmedim.' },
{ s:'klasik', t:'Hiç deniz tutmasını yaşamadım.' },
{ s:'klasik', t:'Hiç saçımı kendim kesmedim.' },
{ s:'klasik', t:'Hiç bir ünlüyle karşılaşmadım.' },
{ s:'klasik', t:'Hiç kamp yapmadım.' },
{ s:'klasik', t:'Hiç yemek yaparken yangın alarmını çalıştırmadım.' },
{ s:'klasik', t:'Hiç bir dizinin bütün sezonunu tek günde bitirmedim.' },
{ s:'klasik', t:'Hiç karaoke yapmadım.' },
{ s:'klasik', t:'Hiç dövme yaptırmadım.' },
{ s:'klasik', t:'Hiç saçımı boyatmadım.' },
{ s:'klasik', t:'Hiç toplu taşımada uyuyakalıp durağı kaçırmadım.' },
{ s:'klasik', t:'Hiç birinin adını yüzüne karşı yanlış söylemedim.' },
{ s:'klasik', t:'Hiç sınavda kopya çekmedim.' },
{ s:'klasik', t:'Hiç bir hayvan beslemedim.' },
{ s:'klasik', t:'Hiç yurt dışında yaşamadım.' },
{ s:'klasik', t:'Hiç ehliyet sınavından kalmadım.' },
{ s:'klasik', t:'Hiç bir konserde en ön sırada olmadım.' },
{ s:'klasik', t:'Hiç telefonumu suya düşürmedim.' },
{ s:'klasik', t:'Hiç doğum günümü unutmadım.' },
{ s:'klasik', t:'Hiç birine yanlışlıkla ekran görüntüsü atmadım.' },
{ s:'klasik', t:'Hiç sabaha kadar oyun oynamadım.' },
{ s:'klasik', t:'Hiç market alışverişinde kartım reddedilmedi.' },
{ s:'klasik', t:'Hiç yürüyen merdivende ters yöne gitmedim.' },
{ s:'klasik', t:'Hiç bir şeyi ters giydiğimi gün ortasında fark etmedim.' },
{ s:'klasik', t:'Hiç arkadaşımın sevgilisinin adını karıştırmadım.' },
{ s:'klasik', t:'Hiç toplantıda mikrofonum açık unutulmadı.' },
{ s:'klasik', t:'Hiç bir yemeği beğenmediğim halde “çok güzel olmuş” demedim.' },
{ s:'klasik', t:'Hiç alarmı kurmayı unutup işe ya da okula geç kalmadım.' },
{ s:'klasik', t:'Hiç bir filmi izlerken ağlamadım.' },
{ s:'klasik', t:'Hiç kendi kendime konuşurken yakalanmadım.' },
{ s:'klasik', t:'Hiç birinin selamını başkasına sandığım için el sallamadım.' },
{ s:'klasik', t:'Hiç sosyal medyada eski bir gönderiyi yanlışlıkla beğenmedim.' },
{ s:'klasik', t:'Hiç tek başıma sinemaya gitmedim.' },
{ s:'klasik', t:'Hiç bir şarkının sözlerini yıllarca yanlış bilmedim.' },
{ s:'klasik', t:'Hiç kapıyı çekip anahtarı içeride bırakmadım.' },
{ s:'klasik', t:'Hiç bisiklete binmeyi öğrenmedim.' },
{ s:'klasik', t:'Hiç yüzme bilmediğimi saklamadım.' },
{ s:'klasik', t:'Hiç stadyumda maç izlemedim.' },
{ s:'klasik', t:'Hiç kar altında yürümekten keyif almadım.' },
{ s:'klasik', t:'Hiç tiyatroya gitmedim.' },
{ s:'klasik', t:'Hiç bir enstrüman çalmayı denemedim.' },
{ s:'klasik', t:'Hiç kendi yaptığım yemeği çöpe atmadım.' },
{ s:'klasik', t:'Hiç markette kaybolup aynı reyona üç kere gelmedim.' },
{ s:'klasik', t:'Hiç asansörde mahsur kalmadım.' },
{ s:'klasik', t:'Hiç bir sınavdan erken çıkmadım.' },
{ s:'klasik', t:'Hiç derste ya da toplantıda uyuyakalmadım.' },
{ s:'klasik', t:'Hiç kuaförden ağlayarak çıkmadım.' },
{ s:'klasik', t:'Hiç telefonumu unutup yarı yoldan geri dönmedim.' },
{ s:'klasik', t:'Hiç bir kitabı yarısında bırakmadım.' },
{ s:'klasik', t:'Hiç yanlış otobüse binmedim.' },
{ s:'klasik', t:'Hiç bana gelen hediyeyi başkasına vermedim.' },
{ s:'klasik', t:'Hiç misafirlikte bir şey kırmadım.' },
{ s:'klasik', t:'Hiç tek başıma restoranda yemek yemedim.' },
{ s:'klasik', t:'Hiç ikinci el bir şey almadım.' },
{ s:'klasik', t:'Hiç kazı kazan ya da piyango almadım.' },
{ s:'klasik', t:'Hiç sokakta gördüğüm bir hayvanı eve götürmedim.' },
{ s:'klasik', t:'Hiç saçımı sıfıra vurmadım.' },
{ s:'klasik', t:'Hiç bağırmaktan sesim kısılmadı.' },
{ s:'klasik', t:'Hiç bir şarkıyı üst üste on kere dinlemedim.' },
{ s:'klasik', t:'Hiç bir filmin sonunu önceden okumadım.' },
{ s:'klasik', t:'Hiç yeni yıla uyuyarak girmedim.' },
{ s:'klasik', t:'Hiç yeni işimin ilk günü geç kalmadım.' },
{ s:'klasik', t:'Hiç yemek siparişini yanlış adrese vermedim.' },
{ s:'klasik', t:'Hiç bir şeyi tamir etmeye çalışıp daha çok bozmadım.' },
{ s:'klasik', t:'Hiç başkasının şarj aletini sahiplenmedim.' },
{ s:'klasik', t:'Hiç bir dizi karakteri öldü diye üzülmedim.' },
{ s:'klasik', t:'Hiç bir hayvandan korkup kaçmadım.' },
{ s:'klasik', t:'Hiç yanlışlıkla birini engellemedim.' },
{ s:'klasik', t:'Hiç bir grup sohbetinden sessizce çıkmadım.' },
{ s:'klasik', t:'Hiç sesli mesajı yanlışlıkla göndermedim.' },
{ s:'klasik', t:'Hiç yirmi fotoğraf çekip hiçbirini beğenmedim.' },
{ s:'klasik', t:'Hiç fotoğraf çekerken dengemi kaybetmedim.' },
{ s:'klasik', t:'Hiç okumadığım bir şeye “okudum” demedim.' },
{ s:'klasik', t:'Hiç sözleşmeyi okumadan onaylamadım.' },
{ s:'klasik', t:'Hiç sırf bir kişi için uygulama indirmedim.' },
{ s:'klasik', t:'Hiç sepeti doldurup satın almadan çıkmadım.' },
{ s:'klasik', t:'Hiç indirim diye ihtiyacım olmayan şeyi almadım.' },
{ s:'klasik', t:'Hiç kaybettiğim eşyayı kendi evimde bulmadım.' },
{ s:'klasik', t:'Hiç elimdeki telefonu aramadım.' },
{ s:'klasik', t:'Hiç birine yanlış isimle hitap etmedim.' },
{ s:'klasik', t:'Hiç görüntülü görüşmede kameranın açık olduğunu unutmadım.' },
{ s:'klasik', t:'Hiç bir randevuyu tamamen unutmadım.' },
{ s:'klasik', t:'Hiç yanlış kişiye “canım” demedim.' },
{ s:'klasik', t:'Hiç anlamadığım bir esprinin ardından gülmedim.' },
{ s:'klasik', t:'Hiç uyuyakaldığım filme “çok güzeldi” demedim.' },
{ s:'klasik', t:'Hiç telefona bakarken bir yere çarpmadım.' },
{ s:'klasik', t:'Hiç itilecek kapıyı çekmeye çalışmadım.' },
{ s:'klasik', t:'Hiç bir kelimeyi yıllarca yanlış telaffuz etmedim.' },
{ s:'klasik', t:'Hiç gittiğim şehirde ters yöne yürümedim.' },
{ s:'klasik', t:'Hiç bavulumu kaybetmedim.' },
{ s:'klasik', t:'Hiç uçağı ya da otobüsü kaçırmadım.' },
{ s:'klasik', t:'Hiç kimliğimi son anda bulmadım.' },
{ s:'klasik', t:'Hiç tarife bakmadan yemek yapıp rezil olmadım.' },
{ s:'klasik', t:'Hiç mutfakta elimi kesmedim.' },
{ s:'klasik', t:'Hiç bir bitkiyi bakarken öldürmedim.' },
{ s:'klasik', t:'Hiç ilk izlenimimde yanılmadım.' },
{ s:'klasik', t:'Hiç bir yere gitmek için bahane uydurup evde kalmadım.' },
{ s:'klasik', t:'Hiç kendi sesimi kayıttan dinleyip irkilmedim.' },
{ s:'klasik', t:'Hiç birinin yanında kendi telefonumdan utanmadım.' },
{ s:'klasik', t:'Hiç bir alışverişte fiyatı görünce vazgeçmedim.' },

/* ------------------------------------------------------------------
   ACI BİBER — 100 (yakın arkadaş grubu için; cinsellik dahil)
------------------------------------------------------------------ */
{ s:'aci', t:'Hiç gece yarısı eski sevgilime mesaj atmadım.' },
{ s:'aci', t:'Hiç birinin sosyal medyasında çok eskiye kaydırıp beğeniye basmadım.' },
{ s:'aci', t:'Hiç yalan söyleyip bir davete gitmekten kurtulmadım.' },
{ s:'aci', t:'Hiç bu masadakilerden birine yalan söylemedim.' },
{ s:'aci', t:'Hiç birinin mesajını okuyup günlerce cevap vermemezlik etmedim.' },
{ s:'aci', t:'Hiç hasta numarası yapıp işe gitmedim.' },
{ s:'aci', t:'Hiç birinin telefonunu izinsiz karıştırmadım.' },
{ s:'aci', t:'Hiç arkadaşımın kırıldığı bir şeyi arkasından anlatmadım.' },
{ s:'aci', t:'Hiç bir ilişkiyi mesajla bitirmedim.' },
{ s:'aci', t:'Hiç iki kişiyle aynı anda yazışmadım.' },
{ s:'aci', t:'Hiç gece kulübünde ağlamadım.' },
{ s:'aci', t:'Hiç ertesi gün bir önceki geceyi hatırlamadığım olmadı.' },
{ s:'aci', t:'Hiç birinin adını sohbetin ortasında sormak zorunda kalmadım.' },
{ s:'aci', t:'Hiç arkadaşımın eşyasını kırıp söylemedim.' },
{ s:'aci', t:'Hiç birine “yoldayım” deyip daha evden çıkmamış olmadım.' },
{ s:'aci', t:'Hiç bu odadakilerden birine gizlice hayranlık duymadım.' },
{ s:'aci', t:'Hiç sarhoşken alışveriş yapmadım.' },
{ s:'aci', t:'Hiç bir arkadaşımın sevgilisini beğenmediğimi söylemedim.' },
{ s:'aci', t:'Hiç kavga ettiğim biriyle hiçbir şey olmamış gibi davranmadım.' },
{ s:'aci', t:'Hiç birini kıskandırmak için bir şey paylaşmadım.' },
{ s:'aci', t:'Hiç birinin doğum gününü hatırlamayıp son anda hediye almadım.' },
{ s:'aci', t:'Hiç toplu fotoğrafta kendimi beğenmediğim için sildirmedim.' },
{ s:'aci', t:'Hiç birine yaşımı ya da maaşımı olduğundan farklı söylemedim.' },
{ s:'aci', t:'Hiç birinin arkasından konuşurken yakalanmadım.' },
{ s:'aci', t:'Hiç bir arkadaşımın sırrını başkasına anlatmadım.' },
{ s:'aci', t:'Hiç taksi beklerken birini ekip kaçmadım.' },
{ s:'aci', t:'Hiç tanımadığım biriyle sabaha kadar konuşmadım.' },
{ s:'aci', t:'Hiç birine “seni sonra ararım” deyip hiç aramadım.' },
{ s:'aci', t:'Hiç bu masadakilerden biri hakkında rüya görmedim.' },
{ s:'aci', t:'Hiç birinin yüzüne gülüp arkasından güldüğüm olmadı.' },

{ s:'aci', t:'Hiç bir gecelik ilişki yaşamadım.' },
{ s:'aci', t:'Hiç tanıştığım gün biriyle öpüşmedim.' },
{ s:'aci', t:'Hiç iş ya da okul çevremden biriyle bir şey yaşamadım.' },
{ s:'aci', t:'Hiç arkadaşımın eski sevgilisiyle bir şey yaşamadım.' },
{ s:'aci', t:'Hiç sevgilimin arkadaşına ilgi duymadım.' },
{ s:'aci', t:'Hiç ev dışında bir yerde birlikte olmadım.' },
{ s:'aci', t:'Hiç üçlü teklifi almadım ya da yapmadım.' },
{ s:'aci', t:'Hiç yatakta yanlış isim söylemedim.' },
{ s:'aci', t:'Hiç birlikteyken gülme krizine girmedim.' },
{ s:'aci', t:'Hiç tanışma uygulamasından biriyle buluşmadım.' },
{ s:'aci', t:'Hiç birine cesur bir fotoğraf göndermedim.' },
{ s:'aci', t:'Hiç yasak bir ilişki yaşamadım.' },
{ s:'aci', t:'Hiç ilk buluşmanın sonunda eve gitmedim.' },
{ s:'aci', t:'Hiç birinin evinden sabah gizlice çıkmadım.' },
{ s:'aci', t:'Hiç komşular duydu mu diye endişelenmedim.' },
{ s:'aci', t:'Hiç eski sevgilimle tekrar bir şey yaşamadım.' },
{ s:'aci', t:'Hiç sevgilim varken başkasını öpmedim.' },
{ s:'aci', t:'Hiç bir ilişkiyi sadece fiziksel çekim için sürdürmedim.' },
{ s:'aci', t:'Hiç “sadece arkadaşız” dediğim biriyle bir şey yaşamadım.' },
{ s:'aci', t:'Hiç tatilde tanıştığım biriyle bir şey yaşamadım.' },
{ s:'aci', t:'Hiç aynı gün iki kişiyle buluşmadım.' },
{ s:'aci', t:'Hiç birinin evinde eşyamı unutmadım.' },
{ s:'aci', t:'Hiç yakalanma korkusu yaşamadım.' },
{ s:'aci', t:'Hiç arabada bir şey yaşamadım.' },
{ s:'aci', t:'Hiç birine ilgimi itiraf edemeden vazgeçmedim.' },
{ s:'aci', t:'Hiç bir ilişkiyi arkadaşlarımdan saklamadım.' },
{ s:'aci', t:'Hiç bu masadakilerden birini çekici bulmadım.' },
{ s:'aci', t:'Hiç birinin sesli mesajını defalarca dinlemedim.' },
{ s:'aci', t:'Hiç partnerimin telefonuna bakmadım.' },
{ s:'aci', t:'Hiç “bir daha olmayacak” deyip tekrar yapmadım.' },
{ s:'aci', t:'Hiç birinin fotoğrafını arkadaşlarıma göstermedim.' },
{ s:'aci', t:'Hiç ayrıldığım kişiye ayrıldığımız gün yazmadım.' },
{ s:'aci', t:'Hiç birini sırf yalnız kalmamak için hayatımda tutmadım.' },
{ s:'aci', t:'Hiç birinin yanında telefonumu ters çevirmedim.' },
{ s:'aci', t:'Hiç bir buluşmadan erken kaçmak için bahane uydurmadım.' },

{ s:'aci', t:'Hiç birini görmemek için yolumu değiştirmedim.' },
{ s:'aci', t:'Hiç arkadaşımdan aldığım borcu geciktirmedim.' },
{ s:'aci', t:'Hiç birinin evinden izinsiz bir şey almadım.' },
{ s:'aci', t:'Hiç sarhoşken birini aramadım.' },
{ s:'aci', t:'Hiç sarhoşken paylaşım yapıp ertesi gün silmedim.' },
{ s:'aci', t:'Hiç birine “meşgulüm” deyip evde yatmadım.' },
{ s:'aci', t:'Hiç bir düğünde ağlamadım.' },
{ s:'aci', t:'Hiç bir davete gitmemek için bahane uydurmadım.' },
{ s:'aci', t:'Hiç iş görüşmesinde abartmadım.' },
{ s:'aci', t:'Hiç özgeçmişimde bir şeyi büyütmedim.' },
{ s:'aci', t:'Hiç yöneticimin arkasından konuşmadım.' },
{ s:'aci', t:'Hiç iş yerinde ağlamadım.' },
{ s:'aci', t:'Hiç olmayan bir toplantı uydurup kaçmadım.' },
{ s:'aci', t:'Hiç birinin fikrini kendi fikrim gibi sunmadım.' },
{ s:'aci', t:'Hiç hesabı bölüşürken az ödemedim.' },
{ s:'aci', t:'Hiç hediyeyi beğenmediğimi saklamadım.' },
{ s:'aci', t:'Hiç bir grup sohbetinde orada olmayanı konuşmadım.' },
{ s:'aci', t:'Hiç bir arkadaşımı kıskanmadım.' },
{ s:'aci', t:'Hiç birinin başarısına içten sevinemediğim olmadı.' },
{ s:'aci', t:'Hiç “seni özledim” deyip özlemediğim olmadı.' },
{ s:'aci', t:'Hiç mesajı görüp saatler sonra “yeni gördüm” demedim.' },
{ s:'aci', t:'Hiç fotoğrafımı düzenleyip paylaşmadım.' },
{ s:'aci', t:'Hiç yaşımı küçültmedim.' },
{ s:'aci', t:'Hiç bir buluşmayı son anda iptal etmedim.' },
{ s:'aci', t:'Hiç birinin adını telefonuma farklı kaydetmedim.' },
{ s:'aci', t:'Hiç eski sevgilimin yeni sevgilisini araştırmadım.' },
{ s:'aci', t:'Hiç birinin hikâyesini defalarca izlemedim.' },
{ s:'aci', t:'Hiç engellediğim birini tekrar takip etmedim.' },
{ s:'aci', t:'Hiç bir kavgayı ben başlatmadım.' },
{ s:'aci', t:'Hiç özür dilemem gerekirken dilemedim.' },
{ s:'aci', t:'Hiç eve kaçta geldiğimi ailemden gizlemedim.' },
{ s:'aci', t:'Hiç birinin yanında bambaşka biri gibi davranmadım.' },
{ s:'aci', t:'Hiç iki arkadaş grubumu birbirinden uzak tutmadım.' },
{ s:'aci', t:'Hiç bu masadakilerden birine hâlâ söylemediğim bir şey kalmadı.' },
{ s:'aci', t:'Hiç birini ilk gördüğümde yargılayıp sonra pişman olmadım.' },
];

/* ---------- Şişe çevirmece: seçilen kişiye görev ---------- */
export const GOREVLER = [
  'Bir hikâye anlat: en son ne zaman utandın?',
  'Soldaki kişiye bir iltifat et.',
  'Telefonundaki son fotoğrafı göster.',
  'Bir kadeh kaldır ve masaya kısa bir konuşma yap.',
  'Grup adına birini seç, o kişi bir yudum alsın.',
  'En sevdiğin şarkının nakaratını söyle.',
  'Bir sırrını açıkla — küçük olabilir.',
  'Karşındakinin taklidini yap.',
  'Son aradığın kişiyi söyle.',
  'Bir yudum al ya da bir doğruyu söyle: seçim senin.',
  'Sağdaki kişiye bir soru sor, cevap vermek zorunda.',
  'Bir dakika boyunca gülmemeye çalış.',
  'En kötü alışverişini anlat.',
  'Masadaki herkese bir kelimeyle sıfat ver.',
  'En çok dinlediğin şarkıyı aç.',
  'Telefonundaki en eski fotoğrafı göster.',
  'Masadaki son mesajını yüksek sesle oku.',
  'Otuz saniye göz teması kur; önce gülen içer.',
  'Sağındaki kişiyle yer değiştir.',
  'Hayatının en iyi anını anlat.',
  'Bir dakika boyunca sadece soru sorarak konuş.',
  'Masadan birini taklit et, bilen bir yudum atlasın.',
  'En büyük pişmanlığını tek cümleyle söyle.',
  'Karşındakine üç soru sor, hepsine dürüst cevap versin.',
  'Bir şarkı seç, masadakiler kime yakıştığını söylesin.',
  'En son ne zaman yalan söylediğini anlat.',
  'Masadaki en iyi giyineni seç ve nedenini söyle.',
  'Bir dakika boyunca hiç konuşma.',
  'En sevdiğin filmi tek cümleyle kötüle.',
  'Çocukken ne olmak istediğini söyle.',
  'Sana en çok benzeyen kişiyi seç, nedenini anlat.',
  'Bir kişi seç; o kişi sana istediği soruyu sorsun.',
  'En çok mesajlaştığın kişiyi söyle.',
  'Bir anını abartarak anlat, masadakiler abartıyı bulsun.',
  'Sıradaki turda kimin çevireceğini sen seç.',
  'Masaya bir kural koy, bu tur boyunca geçerli olsun.',
  'En utanç verici müzik zevkini itiraf et.',
  'Kadeh kaldır: masadaki birine teşekkür et.',
  'Gözlerini kapat, birini işaret et; o kişi bir yudum alsın.',
  'Bugün kimseye söylemediğin bir şeyi söyle.',
  'Masadan birine bir iyilik sözü ver.',
  'En son kimi aradın, neden aradın?',
  'Bir espri yap; kimse gülmezse sen içersin.',
  'Sana en son kim “seni özledim” dedi?',
  'Bir dakikada üç kişiyi güldürmeye çalış.',
  'Masadaki en iyi hikâye anlatıcısını seç, o bir hikâye anlatsın.',
  'Bir yudum al ya da sıradaki soruyu sen sor.',
  'Telefonunun duvar kâğıdını göster.',
  'Masadakilerden birine yeni bir lakap tak.',
  'Bir dakika boyunca herkese “sen” yerine adıyla hitap et.',
];

/* ---------- Bil Bakalım! — cevabı sayı olan sorular ----------
   c: doğru cevap · b: birim · not: cevap açılınca gösterilen açıklama.
   Tahmin soruları hesabıyla birlikte veriliyor; uydurma sayı yok.        */
export const SORULAR = [
/* --- dünya, coğrafya --- */
{ t:'Everest Tepesi kaç metre?', c:8849, b:'m', not:'2020’de Nepal ve Çin’in ortak ölçümüyle güncellendi.' },
{ t:'Dünyanın ekvator çevresi kaç kilometre?', c:40075, b:'km', not:'Kutuplardan geçen çevre biraz daha kısa: 40.008 km.' },
{ t:'Okyanusun en derin noktası (Mariana Çukuru) kaç metre?', c:10994, b:'m', not:'Challenger Derinliği; ölçümlere göre 10.900–11.000 m arası veriliyor.' },
{ t:'Nil Nehri kaç kilometre?', c:6650, b:'km', not:'Amazon ile “en uzun nehir” yarışı ölçüm yöntemine göre değişiyor.' },
{ t:'Rusya’nın yüzölçümü kaç kilometrekare?', c:17098242, b:'km²', not:'Dünya kara yüzeyinin yaklaşık sekizde biri.' },
{ t:'Türkiye’nin yüzölçümü kaç kilometrekare?', c:783562, b:'km²', not:'Göller dahil toplam alan.' },
{ t:'Vatikan’ın yüzölçümü kaç kilometrekare?', c:0.44, b:'km²', not:'Dünyanın en küçük ülkesi; Taksim Meydanı ve çevresi kadar.' },
{ t:'Dünyada kaç ülke var (BM üyesi)?', c:193, b:'ülke', not:'Birleşmiş Milletler üye sayısı. Gözlemci statüsündekiler hariç.' },
{ t:'Türkiye’de kaç il var?', c:81, b:'il', not:'Son eklenen il 1999’da Düzce.' },
{ t:'Çin Seddi kaç kilometre?', c:21196, b:'km', not:'2012 resmî ölçümü; bütün kollar ve dallar dahil.' },

/* --- uzay --- */
{ t:'Ay ile Dünya arası ortalama kaç kilometre?', c:384400, b:'km', not:'Yörünge eliptik olduğu için 363.300 ile 405.500 km arasında değişir.' },
{ t:'Güneş ile Dünya arası kaç milyon kilometre?', c:150, b:'milyon km', not:'Bu uzaklığa “astronomik birim” deniyor.' },
{ t:'Işık saniyede kaç kilometre yol alır?', c:299792, b:'km/sn', not:'Boşlukta; tam değer 299.792,458 km/sn.' },
{ t:'Güneş ışığı Dünya’ya kaç dakikada ulaşır?', c:8, b:'dakika', not:'Yaklaşık 8 dakika 20 saniye.' },
{ t:'Uluslararası Uzay İstasyonu Dünya’yı günde kaç kez turlar?', c:16, b:'tur', not:'Yaklaşık 90 dakikada bir tur atıyor.' },
{ t:'Güneş Sistemi’nde kaç gezegen var?', c:8, b:'gezegen', not:'Plüton 2006’da cüce gezegen sınıfına alındı.' },
{ t:'Mars’ta bir gün kaç saat sürer?', c:24.6, b:'saat', not:'Dünya gününden yaklaşık 40 dakika uzun.' },
{ t:'Ay’da yerçekimi Dünya’nın kaçta biri?', c:6, b:'’da biri', not:'Dünya’da 60 kg olan biri Ay’da 10 kg gelir.' },

/* --- insan vücudu --- */
{ t:'Yetişkin bir insanda kaç kemik var?', c:206, b:'kemik', not:'Bebeklerde yaklaşık 300; büyürken bir kısmı kaynaşıyor.' },
{ t:'Kalp günde ortalama kaç kez atar?', c:100000, b:'atış', not:'Dakikada ~70 atış × 60 × 24 ≈ 100.800.' },
{ t:'Bir insanın vücudunda kaç litre kan var?', c:5, b:'litre', not:'Yetişkin ortalaması; vücut ağırlığının ~%7’si.' },
{ t:'İnsan beyni kaç gram?', c:1400, b:'gram', not:'Yetişkin ortalaması; vücut ağırlığının %2’si ama enerjinin %20’sini kullanır.' },
{ t:'Kafada ortalama kaç saç teli var?', c:100000, b:'tel', not:'Saç rengine göre değişir; sarışınlarda daha fazla, kızıllarda daha az.' },
{ t:'İnsan dakikada ortalama kaç kez göz kırpar?', c:17, b:'kez', not:'Dakikada 15–20 arası; ekrana bakarken belirgin şekilde azalıyor.' },
{ t:'Yetişkin bir insanın vücudunun yüzde kaçı su?', c:60, b:'%', not:'Yaşa ve vücut yapısına göre %55–65 arası.' },
{ t:'İnsan vücudunda kaç kas var?', c:600, b:'kas', not:'Sayım yöntemine göre 600–650 arasında veriliyor.' },
{ t:'Dil üzerinde kaç tat tomurcuğu var?', c:10000, b:'tomurcuk', not:'Yaşla birlikte azalıyor.' },

/* --- hayvanlar --- */
{ t:'Zürafanın boynunda kaç omur var?', c:7, b:'omur', not:'İnsanla aynı sayıda — sadece her biri çok uzun.' },
{ t:'Ahtapotun kaç kalbi var?', c:3, b:'kalp', not:'İkisi solungaçlara, biri vücuda kan pompalar.' },
{ t:'Bir fil kaç ay hamile kalır?', c:22, b:'ay', not:'Kara hayvanları arasındaki en uzun gebelik.' },
{ t:'Bir karınca kendi ağırlığının kaç katını taşıyabilir?', c:50, b:'kat', not:'Türe göre 10–50 kat arası veriliyor.' },
{ t:'Bir arı kovanında yazın kaç arı bulunur?', c:50000, b:'arı', not:'Mevsime göre 20.000 ile 80.000 arasında değişiyor.' },
{ t:'Sinek saniyede kaç kez kanat çırpar?', c:200, b:'kez', not:'Bu yüzden vızıltısı duyulabilir bir sese dönüşüyor.' },
{ t:'Mavi balina kaç metre uzunlukta olabilir?', c:30, b:'m', not:'Yaşamış en büyük hayvan; 150 tona kadar çıkabiliyor.' },
{ t:'Bir çita en fazla saatte kaç kilometre hızlanır?', c:110, b:'km/s', not:'Bu hızı yalnızca birkaç yüz metre koruyabiliyor.' },

/* --- spor, ölçüler --- */
{ t:'Maraton kaç kilometre?', c:42.195, b:'km', not:'1908 Londra Olimpiyatları’nda kraliyet locasına göre ayarlandı.' },
{ t:'Olimpik yüzme havuzu kaç metre?', c:50, b:'m', not:'Genişliği 25 m, on kulvar.' },
{ t:'Basketbol potası yerden kaç santimetre yükseklikte?', c:305, b:'cm', not:'Tam 10 ayak.' },
{ t:'Satranç tahtasında kaç kare var?', c:64, b:'kare', not:'8×8; her oyuncu 16 taşla başlar.' },
{ t:'Piyanoda kaç tuş var?', c:88, b:'tuş', not:'52 beyaz, 36 siyah.' },
{ t:'Bir futbol maçı kaç dakika (uzatmalar hariç)?', c:90, b:'dakika', not:'İki devre 45’er dakika.' },
{ t:'Tavla pulu sayısı toplam kaç?', c:30, b:'pul', not:'Her oyuncuda 15 pul.' },

/* --- zaman, sayılar --- */
{ t:'Bir yılda kaç saniye var?', c:31536000, b:'saniye', not:'365 × 24 × 60 × 60.' },
{ t:'Bir milyon saniye kaç gündür?', c:11.6, b:'gün', not:'Bir milyar saniye ise yaklaşık 31,7 yıl.' },
{ t:'İnsan DNA’sında kaç kromozom var?', c:46, b:'kromozom', not:'23 çift.' },
{ t:'Rubik küpünün kaç farklı dizilişi var (kentilyon)?', c:43, b:'kentilyon', not:'43.252.003.274.489.856.000 — yani 43 kentilyon.' },

/* --- tarih --- */
{ t:'Türkiye Cumhuriyeti hangi yıl kuruldu?', c:1923, b:'', not:'29 Ekim 1923.' },
{ t:'İstanbul hangi yıl fethedildi?', c:1453, b:'', not:'29 Mayıs 1453.' },
{ t:'İnsan Ay’a ilk kez hangi yıl ayak bastı?', c:1969, b:'', not:'20 Temmuz 1969, Apollo 11.' },
{ t:'Titanic hangi yıl battı?', c:1912, b:'', not:'15 Nisan 1912, ilk seferinde.' },
{ t:'Berlin Duvarı hangi yıl yıkıldı?', c:1989, b:'', not:'9 Kasım 1989.' },
{ t:'İlk iPhone hangi yıl tanıtıldı?', c:2007, b:'', not:'9 Ocak 2007’de tanıtıldı, Haziran’da satışa çıktı.' },
{ t:'İkinci Dünya Savaşı kaç yıl sürdü?', c:6, b:'yıl', not:'1939–1945.' },

/* --- yapılar --- */
{ t:'Eiffel Kulesi kaç metre?', c:330, b:'m', not:'Antenlerle birlikte; yapıldığında 300 m idi.' },
{ t:'Burj Khalifa kaç metre?', c:828, b:'m', not:'Dünyanın en yüksek binası, 163 kat.' },
{ t:'Galata Kulesi kaç metre?', c:67, b:'m', not:'Bulunduğu tepeyle birlikte deniz seviyesinden ~140 m.' },
{ t:'Mısır’daki Büyük Piramit kaç metre (bugünkü hâli)?', c:139, b:'m', not:'Yapıldığında 146 m idi; dış kaplaması aşınmış.' },
{ t:'Özgürlük Anıtı kaidesiyle birlikte kaç metre?', c:93, b:'m', not:'Yalnızca heykel 46 m.' },

/* --- gündelik hayat, tahmin soruları --- */
{ t:'Bir insan ömrü boyunca yaklaşık kaç kilo yemek yer?', c:44000, b:'kg', not:'Günde ~1,5 kg × 365 × 80 yıl ≈ 44 ton.' },
{ t:'Bir insan ömrü boyunca yaklaşık kaç yıl uyur?', c:26, b:'yıl', not:'Günde 8 saat × 80 yıl = ömrün üçte biri.' },
{ t:'Bir insanın kalbi ömrü boyunca yaklaşık kaç kez atar (milyar)?', c:2.9, b:'milyar', not:'Dakikada 70 × 60 × 24 × 365 × 80 ≈ 2,9 milyar.' },
{ t:'Bir insan ömrü boyunca yaklaşık kaç litre su içer?', c:58000, b:'litre', not:'Günde 2 litre × 365 × 80 yıl.' },
{ t:'Saç ayda ortalama kaç santimetre uzar?', c:1.25, b:'cm', not:'Yılda ~15 cm; 80 yılda 12 metreye yakın saç üretiliyor.' },
{ t:'Bir insan günde ortalama kaç kelime konuşur?', c:16000, b:'kelime', not:'Araştırmalarda kadın ve erkek ortalamaları birbirine yakın çıkıyor.' },
{ t:'Bir insan günde ortalama kaç kez telefonuna bakar?', c:58, b:'kez', not:'Ekran zamanı araştırmalarında 50–80 arası ölçülüyor.' },
{ t:'Bir A4 kâğıdı kaç kez ikiye katlanabilir (gerçekte)?', c:7, b:'kez', not:'Her katlamada kalınlık iki katına çıkıyor; 7’den sonrası elle mümkün değil.' },
{ t:'Bir fincan filtre kahvede kaç miligram kafein var?', c:95, b:'mg', not:'Demleme yöntemine göre 70–140 mg arası.' },
{ t:'Bir muzun içinde kaç kalori var?', c:105, b:'kalori', not:'Orta boy, ~118 gram.' },
{ t:'Bir insan nefes almadan ortalama kaç saniye durabilir?', c:60, b:'saniye', not:'Antrenmansız ortalama; rekorlar 20 dakikanın üzerinde.' },
{ t:'Dünyada her saniye yaklaşık kaç bebek doğuyor?', c:4, b:'bebek', not:'Yılda ~130 milyon doğum.' },
{ t:'Dünya nüfusu kaç milyar?', c:8, b:'milyar', not:'2022 sonunda 8 milyarı geçti.' },
{ t:'İstanbul’un nüfusu kaç milyon?', c:15.7, b:'milyon', not:'TÜİK 2023 verisi; Türkiye nüfusunun beşte birinden fazlası.' },
{ t:'Türkiye’nin nüfusu kaç milyon?', c:85, b:'milyon', not:'2023 TÜİK verisine göre 85,3 milyon.' },
{ t:'Bir insan ömrü boyunca yaklaşık kaç adım atar (milyon)?', c:200, b:'milyon', not:'Günde ~7.000 adım × 365 × 80 yıl.' },
{ t:'Bir yılda ortalama kaç kez hapşırırız?', c:400, b:'kez', not:'Günde ~1 kez; alerjisi olanlarda çok daha fazla.' },
{ t:'Bir kilo bal için arılar yaklaşık kaç milyon çiçeği ziyaret eder?', c:4, b:'milyon', not:'Bir arı ömrü boyunca ancak bir çay kaşığı bal üretebiliyor.' },
];

export const NHIE_SEVIYE = { klasik: 'Klasik', aci: 'Acı biber', hepsi: 'Karışık' };

/** Kullanılmışları atlayarak rastgele bir öğe seçer. → {i, item} */
export function pick(list, kullanilan, rnd = Math.random) {
  const musait = list.map((_, i) => i).filter(i => !kullanilan.includes(i));
  const havuz = musait.length ? musait : list.map((_, i) => i);
  if (!musait.length) kullanilan.length = 0;
  const i = havuz[Math.floor(rnd() * havuz.length)];
  kullanilan.push(i);
  return { i, item: list[i] };
}
