/* ============================================================
   deck.js — oyun içerikleri (tek kaynak).
   Hem tarayıcı hem sunucu bu dosyayı kullanır.

   Ben Hiç… seviyeleri:
     'klasik' → masada kim olursa olsun rahat sorulur
     'aci'    → yakın arkadaş grubu; ilişkiler, itiraflar, cinsellik
   ============================================================ */

export const NHIE = [
/* ------------------------------------------------------------------
   KLASİK — 100
------------------------------------------------------------------ */
{ s:'klasik', t:'Hiç uçağa binmedim.' },
{ s:'klasik', t:'Hiç deniz tutmasını yaşamadım.' },
{ s:'klasik', t:'Hiç saçımı kendim kesmedim.' },
{ s:'klasik', t:'Hiç bir ünlüyle karşılaşmadım.' },
{ s:'klasik', t:'Hiç kamp yapmadım.' },
{ s:'klasik', t:'Hiç yemek yaparken yangın alarmını çalıştırmadım.' },
{ s:'klasik', t:'Hiç bir dizinin bütün sezonunu tek günde bitirmedim.' },
{ s:'klasik', t:'Hiç karaoke yapmadım.' },
{ s:'klasik', t:'Hiç dövme yaptırmadım.' },
{ s:'klasik', t:'Hiç saçımı boyatmadım.' },
{ s:'klasik', t:'Hiç toplu taşımada uyuyakalıp durağı kaçırmadım.' },
{ s:'klasik', t:'Hiç birinin adını yüzüne karşı yanlış söylemedim.' },
{ s:'klasik', t:'Hiç sınavda kopya çekmedim.' },
{ s:'klasik', t:'Hiç bir hayvan beslemedim.' },
{ s:'klasik', t:'Hiç yurt dışında yaşamadım.' },
{ s:'klasik', t:'Hiç ehliyet sınavından kalmadım.' },
{ s:'klasik', t:'Hiç bir konserde en ön sırada olmadım.' },
{ s:'klasik', t:'Hiç telefonumu suya düşürmedim.' },
{ s:'klasik', t:'Hiç doğum günümü unutmadım.' },
{ s:'klasik', t:'Hiç birine yanlışlıkla ekran görüntüsü atmadım.' },
{ s:'klasik', t:'Hiç sabaha kadar oyun oynamadım.' },
{ s:'klasik', t:'Hiç market alışverişinde kartım reddedilmedi.' },
{ s:'klasik', t:'Hiç yürüyen merdivende ters yöne gitmedim.' },
{ s:'klasik', t:'Hiç bir şeyi ters giydiğimi gün ortasında fark etmedim.' },
{ s:'klasik', t:'Hiç arkadaşımın sevgilisinin adını karıştırmadım.' },
{ s:'klasik', t:'Hiç toplantıda mikrofonum açık unutulmadı.' },
{ s:'klasik', t:'Hiç bir yemeği beğenmediğim halde “çok güzel olmuş” demedim.' },
{ s:'klasik', t:'Hiç alarmı kurmayı unutup işe ya da okula geç kalmadım.' },
{ s:'klasik', t:'Hiç bir filmi izlerken ağlamadım.' },
{ s:'klasik', t:'Hiç kendi kendime konuşurken yakalanmadım.' },
{ s:'klasik', t:'Hiç birinin selamını başkasına sandığım için el sallamadım.' },
{ s:'klasik', t:'Hiç sosyal medyada eski bir gönderiyi yanlışlıkla beğenmedim.' },
{ s:'klasik', t:'Hiç tek başıma sinemaya gitmedim.' },
{ s:'klasik', t:'Hiç bir şarkının sözlerini yıllarca yanlış bilmedim.' },
{ s:'klasik', t:'Hiç kapıyı çekip anahtarı içeride bırakmadım.' },
{ s:'klasik', t:'Hiç bisiklete binmeyi öğrenmedim.' },
{ s:'klasik', t:'Hiç yüzme bilmediğimi saklamadım.' },
{ s:'klasik', t:'Hiç stadyumda maç izlemedim.' },
{ s:'klasik', t:'Hiç kar altında yürümekten keyif almadım.' },
{ s:'klasik', t:'Hiç tiyatroya gitmedim.' },
{ s:'klasik', t:'Hiç bir enstrüman çalmayı denemedim.' },
{ s:'klasik', t:'Hiç kendi yaptığım yemeği çöpe atmadım.' },
{ s:'klasik', t:'Hiç markette kaybolup aynı reyona üç kere gelmedim.' },
{ s:'klasik', t:'Hiç asansörde mahsur kalmadım.' },
{ s:'klasik', t:'Hiç bir sınavdan erken çıkmadım.' },
{ s:'klasik', t:'Hiç derste ya da toplantıda uyuyakalmadım.' },
{ s:'klasik', t:'Hiç kuaförden ağlayarak çıkmadım.' },
{ s:'klasik', t:'Hiç telefonumu unutup yarı yoldan geri dönmedim.' },
{ s:'klasik', t:'Hiç bir kitabı yarısında bırakmadım.' },
{ s:'klasik', t:'Hiç yanlış otobüse binmedim.' },
{ s:'klasik', t:'Hiç bana gelen hediyeyi başkasına vermedim.' },
{ s:'klasik', t:'Hiç misafirlikte bir şey kırmadım.' },
{ s:'klasik', t:'Hiç tek başıma restoranda yemek yemedim.' },
{ s:'klasik', t:'Hiç ikinci el bir şey almadım.' },
{ s:'klasik', t:'Hiç kazı kazan ya da piyango almadım.' },
{ s:'klasik', t:'Hiç sokakta gördüğüm bir hayvanı eve götürmedim.' },
{ s:'klasik', t:'Hiç saçımı sıfıra vurmadım.' },
{ s:'klasik', t:'Hiç bağırmaktan sesim kısılmadı.' },
{ s:'klasik', t:'Hiç bir şarkıyı üst üste on kere dinlemedim.' },
{ s:'klasik', t:'Hiç bir filmin sonunu önceden okumadım.' },
{ s:'klasik', t:'Hiç yeni yıla uyuyarak girmedim.' },
{ s:'klasik', t:'Hiç yeni işimin ilk günü geç kalmadım.' },
{ s:'klasik', t:'Hiç yemek siparişini yanlış adrese vermedim.' },
{ s:'klasik', t:'Hiç bir şeyi tamir etmeye çalışıp daha çok bozmadım.' },
{ s:'klasik', t:'Hiç başkasının şarj aletini sahiplenmedim.' },
{ s:'klasik', t:'Hiç bir dizi karakteri öldü diye üzülmedim.' },
{ s:'klasik', t:'Hiç bir hayvandan korkup kaçmadım.' },
{ s:'klasik', t:'Hiç yanlışlıkla birini engellemedim.' },
{ s:'klasik', t:'Hiç bir grup sohbetinden sessizce çıkmadım.' },
{ s:'klasik', t:'Hiç sesli mesajı yanlışlıkla göndermedim.' },
{ s:'klasik', t:'Hiç yirmi fotoğraf çekip hiçbirini beğenmedim.' },
{ s:'klasik', t:'Hiç fotoğraf çekerken dengemi kaybetmedim.' },
{ s:'klasik', t:'Hiç okumadığım bir şeye “okudum” demedim.' },
{ s:'klasik', t:'Hiç sözleşmeyi okumadan onaylamadım.' },
{ s:'klasik', t:'Hiç sırf bir kişi için uygulama indirmedim.' },
{ s:'klasik', t:'Hiç sepeti doldurup satın almadan çıkmadım.' },
{ s:'klasik', t:'Hiç indirim diye ihtiyacım olmayan şeyi almadım.' },
{ s:'klasik', t:'Hiç kaybettiğim eşyayı kendi evimde bulmadım.' },
{ s:'klasik', t:'Hiç elimdeki telefonu aramadım.' },
{ s:'klasik', t:'Hiç birine yanlış isimle hitap etmedim.' },
{ s:'klasik', t:'Hiç görüntülü görüşmede kameranın açık olduğunu unutmadım.' },
{ s:'klasik', t:'Hiç bir randevuyu tamamen unutmadım.' },
{ s:'klasik', t:'Hiç yanlış kişiye “canım” demedim.' },
{ s:'klasik', t:'Hiç anlamadığım bir esprinin ardından gülmedim.' },
{ s:'klasik', t:'Hiç uyuyakaldığım filme “çok güzeldi” demedim.' },
{ s:'klasik', t:'Hiç telefona bakarken bir yere çarpmadım.' },
{ s:'klasik', t:'Hiç itilecek kapıyı çekmeye çalışmadım.' },
{ s:'klasik', t:'Hiç bir kelimeyi yıllarca yanlış telaffuz etmedim.' },
{ s:'klasik', t:'Hiç gittiğim şehirde ters yöne yürümedim.' },
{ s:'klasik', t:'Hiç bavulumu kaybetmedim.' },
{ s:'klasik', t:'Hiç uçağı ya da otobüsü kaçırmadım.' },
{ s:'klasik', t:'Hiç kimliğimi son anda bulmadım.' },
{ s:'klasik', t:'Hiç tarife bakmadan yemek yapıp rezil olmadım.' },
{ s:'klasik', t:'Hiç mutfakta elimi kesmedim.' },
{ s:'klasik', t:'Hiç bir bitkiyi bakarken öldürmedim.' },
{ s:'klasik', t:'Hiç ilk izlenimimde yanılmadım.' },
{ s:'klasik', t:'Hiç bir yere gitmek için bahane uydurup evde kalmadım.' },
{ s:'klasik', t:'Hiç kendi sesimi kayıttan dinleyip irkilmedim.' },
{ s:'klasik', t:'Hiç birinin yanında kendi telefonumdan utanmadım.' },
{ s:'klasik', t:'Hiç bir alışverişte fiyatı görünce vazgeçmedim.' },

/* ------------------------------------------------------------------
   ACI BİBER — 100 (yakın arkadaş grubu için; cinsellik dahil)
------------------------------------------------------------------ */
{ s:'aci', t:'Hiç gece yarısı eski sevgilime mesaj atmadım.' },
{ s:'aci', t:'Hiç birinin sosyal medyasında çok eskiye kaydırıp beğeniye basmadım.' },
{ s:'aci', t:'Hiç yalan söyleyip bir davete gitmekten kurtulmadım.' },
{ s:'aci', t:'Hiç bu masadakilerden birine yalan söylemedim.' },
{ s:'aci', t:'Hiç birinin mesajını okuyup günlerce cevap vermemezlik etmedim.' },
{ s:'aci', t:'Hiç hasta numarası yapıp işe gitmedim.' },
{ s:'aci', t:'Hiç birinin telefonunu izinsiz karıştırmadım.' },
{ s:'aci', t:'Hiç arkadaşımın kırıldığı bir şeyi arkasından anlatmadım.' },
{ s:'aci', t:'Hiç bir ilişkiyi mesajla bitirmedim.' },
{ s:'aci', t:'Hiç iki kişiyle aynı anda yazışmadım.' },
{ s:'aci', t:'Hiç gece kulübünde ağlamadım.' },
{ s:'aci', t:'Hiç ertesi gün bir önceki geceyi hatırlamadığım olmadı.' },
{ s:'aci', t:'Hiç birinin adını sohbetin ortasında sormak zorunda kalmadım.' },
{ s:'aci', t:'Hiç arkadaşımın eşyasını kırıp söylemedim.' },
{ s:'aci', t:'Hiç birine “yoldayım” deyip daha evden çıkmamış olmadım.' },
{ s:'aci', t:'Hiç bu odadakilerden birine gizlice hayranlık duymadım.' },
{ s:'aci', t:'Hiç sarhoşken alışveriş yapmadım.' },
{ s:'aci', t:'Hiç bir arkadaşımın sevgilisini beğenmediğimi söylemedim.' },
{ s:'aci', t:'Hiç kavga ettiğim biriyle hiçbir şey olmamış gibi davranmadım.' },
{ s:'aci', t:'Hiç birini kıskandırmak için bir şey paylaşmadım.' },
{ s:'aci', t:'Hiç birinin doğum gününü hatırlamayıp son anda hediye almadım.' },
{ s:'aci', t:'Hiç toplu fotoğrafta kendimi beğenmediğim için sildirmedim.' },
{ s:'aci', t:'Hiç birine yaşımı ya da maaşımı olduğundan farklı söylemedim.' },
{ s:'aci', t:'Hiç birinin arkasından konuşurken yakalanmadım.' },
{ s:'aci', t:'Hiç bir arkadaşımın sırrını başkasına anlatmadım.' },
{ s:'aci', t:'Hiç taksi beklerken birini ekip kaçmadım.' },
{ s:'aci', t:'Hiç tanımadığım biriyle sabaha kadar konuşmadım.' },
{ s:'aci', t:'Hiç birine “seni sonra ararım” deyip hiç aramadım.' },
{ s:'aci', t:'Hiç bu masadakilerden biri hakkında rüya görmedim.' },
{ s:'aci', t:'Hiç birinin yüzüne gülüp arkasından güldüğüm olmadı.' },

{ s:'aci', t:'Hiç bir gecelik ilişki yaşamadım.' },
{ s:'aci', t:'Hiç tanıştığım gün biriyle öpüşmedim.' },
{ s:'aci', t:'Hiç iş ya da okul çevremden biriyle bir şey yaşamadım.' },
{ s:'aci', t:'Hiç arkadaşımın eski sevgilisiyle bir şey yaşamadım.' },
{ s:'aci', t:'Hiç sevgilimin arkadaşına ilgi duymadım.' },
{ s:'aci', t:'Hiç ev dışında bir yerde birlikte olmadım.' },
{ s:'aci', t:'Hiç üçlü teklifi almadım ya da yapmadım.' },
{ s:'aci', t:'Hiç yatakta yanlış isim söylemedim.' },
{ s:'aci', t:'Hiç birlikteyken gülme krizine girmedim.' },
{ s:'aci', t:'Hiç tanışma uygulamasından biriyle buluşmadım.' },
{ s:'aci', t:'Hiç birine cesur bir fotoğraf göndermedim.' },
{ s:'aci', t:'Hiç yasak bir ilişki yaşamadım.' },
{ s:'aci', t:'Hiç ilk buluşmanın sonunda eve gitmedim.' },
{ s:'aci', t:'Hiç birinin evinden sabah gizlice çıkmadım.' },
{ s:'aci', t:'Hiç komşular duydu mu diye endişelenmedim.' },
{ s:'aci', t:'Hiç eski sevgilimle tekrar bir şey yaşamadım.' },
{ s:'aci', t:'Hiç sevgilim varken başkasını öpmedim.' },
{ s:'aci', t:'Hiç bir ilişkiyi sadece fiziksel çekim için sürdürmedim.' },
{ s:'aci', t:'Hiç “sadece arkadaşız” dediğim biriyle bir şey yaşamadım.' },
{ s:'aci', t:'Hiç tatilde tanıştığım biriyle bir şey yaşamadım.' },
{ s:'aci', t:'Hiç aynı gün iki kişiyle buluşmadım.' },
{ s:'aci', t:'Hiç birinin evinde eşyamı unutmadım.' },
{ s:'aci', t:'Hiç yakalanma korkusu yaşamadım.' },
{ s:'aci', t:'Hiç arabada bir şey yaşamadım.' },
{ s:'aci', t:'Hiç birine ilgimi itiraf edemeden vazgeçmedim.' },
{ s:'aci', t:'Hiç bir ilişkiyi arkadaşlarımdan saklamadım.' },
{ s:'aci', t:'Hiç bu masadakilerden birini çekici bulmadım.' },
{ s:'aci', t:'Hiç birinin sesli mesajını defalarca dinlemedim.' },
{ s:'aci', t:'Hiç partnerimin telefonuna bakmadım.' },
{ s:'aci', t:'Hiç “bir daha olmayacak” deyip tekrar yapmadım.' },
{ s:'aci', t:'Hiç birinin fotoğrafını arkadaşlarıma göstermedim.' },
{ s:'aci', t:'Hiç ayrıldığım kişiye ayrıldığımız gün yazmadım.' },
{ s:'aci', t:'Hiç birini sırf yalnız kalmamak için hayatımda tutmadım.' },
{ s:'aci', t:'Hiç birinin yanında telefonumu ters çevirmedim.' },
{ s:'aci', t:'Hiç bir buluşmadan erken kaçmak için bahane uydurmadım.' },

{ s:'aci', t:'Hiç birini görmemek için yolumu değiştirmedim.' },
{ s:'aci', t:'Hiç arkadaşımdan aldığım borcu geciktirmedim.' },
{ s:'aci', t:'Hiç birinin evinden izinsiz bir şey almadım.' },
{ s:'aci', t:'Hiç sarhoşken birini aramadım.' },
{ s:'aci', t:'Hiç sarhoşken paylaşım yapıp ertesi gün silmedim.' },
{ s:'aci', t:'Hiç birine “meşgulüm” deyip evde yatmadım.' },
{ s:'aci', t:'Hiç bir düğünde ağlamadım.' },
{ s:'aci', t:'Hiç bir davete gitmemek için bahane uydurmadım.' },
{ s:'aci', t:'Hiç iş görüşmesinde abartmadım.' },
{ s:'aci', t:'Hiç özgeçmişimde bir şeyi büyütmedim.' },
{ s:'aci', t:'Hiç yöneticimin arkasından konuşmadım.' },
{ s:'aci', t:'Hiç iş yerinde ağlamadım.' },
{ s:'aci', t:'Hiç olmayan bir toplantı uydurup kaçmadım.' },
{ s:'aci', t:'Hiç birinin fikrini kendi fikrim gibi sunmadım.' },
{ s:'aci', t:'Hiç hesabı bölüşürken az ödemedim.' },
{ s:'aci', t:'Hiç hediyeyi beğenmediğimi saklamadım.' },
{ s:'aci', t:'Hiç bir grup sohbetinde orada olmayanı konuşmadım.' },
{ s:'aci', t:'Hiç bir arkadaşımı kıskanmadım.' },
{ s:'aci', t:'Hiç birinin başarısına içten sevinemediğim olmadı.' },
{ s:'aci', t:'Hiç “seni özledim” deyip özlemediğim olmadı.' },
{ s:'aci', t:'Hiç mesajı görüp saatler sonra “yeni gördüm” demedim.' },
{ s:'aci', t:'Hiç fotoğrafımı düzenleyip paylaşmadım.' },
{ s:'aci', t:'Hiç yaşımı küçültmedim.' },
{ s:'aci', t:'Hiç bir buluşmayı son anda iptal etmedim.' },
{ s:'aci', t:'Hiç birinin adını telefonuma farklı kaydetmedim.' },
{ s:'aci', t:'Hiç eski sevgilimin yeni sevgilisini araştırmadım.' },
{ s:'aci', t:'Hiç birinin hikâyesini defalarca izlemedim.' },
{ s:'aci', t:'Hiç engellediğim birini tekrar takip etmedim.' },
{ s:'aci', t:'Hiç bir kavgayı ben başlatmadım.' },
{ s:'aci', t:'Hiç özür dilemem gerekirken dilemedim.' },
{ s:'aci', t:'Hiç eve kaçta geldiğimi ailemden gizlemedim.' },
{ s:'aci', t:'Hiç birinin yanında bambaşka biri gibi davranmadım.' },
{ s:'aci', t:'Hiç iki arkadaş grubumu birbirinden uzak tutmadım.' },
{ s:'aci', t:'Hiç bu masadakilerden birine hâlâ söylemediğim bir şey kalmadı.' },
{ s:'aci', t:'Hiç birini ilk gördüğümde yargılayıp sonra pişman olmadım.' },
];

/* ---------- Şişe çevirmece: seçilen kişiye görev ---------- */
export const GOREVLER = [
  'Bir hikâye anlat: en son ne zaman utandın?',
  'Soldaki kişiye bir iltifat et.',
  'Telefonundaki son fotoğrafı göster.',
  'Bir kadeh kaldır ve masaya kısa bir konuşma yap.',
  'Grup adına birini seç, o kişi bir yudum alsın.',
  'En sevdiğin şarkının nakaratını söyle.',
  'Bir sırrını açıkla — küçük olabilir.',
  'Karşındakinin taklidini yap.',
  'Son aradığın kişiyi söyle.',
  'Bir yudum al ya da bir doğruyu söyle: seçim senin.',
  'Sağdaki kişiye bir soru sor, cevap vermek zorunda.',
  'Bir dakika boyunca gülmemeye çalış.',
  'En kötü alışverişini anlat.',
  'Masadaki herkese bir kelimeyle sıfat ver.',
  'En çok dinlediğin şarkıyı aç.',
  'Telefonundaki en eski fotoğrafı göster.',
  'Masadaki son mesajını yüksek sesle oku.',
  'Otuz saniye göz teması kur; önce gülen içer.',
  'Sağındaki kişiyle yer değiştir.',
  'Hayatının en iyi anını anlat.',
  'Bir dakika boyunca sadece soru sorarak konuş.',
  'Masadan birini taklit et, bilen bir yudum atlasın.',
  'En büyük pişmanlığını tek cümleyle söyle.',
  'Karşındakine üç soru sor, hepsine dürüst cevap versin.',
  'Bir şarkı seç, masadakiler kime yakıştığını söylesin.',
  'En son ne zaman yalan söylediğini anlat.',
  'Masadaki en iyi giyineni seç ve nedenini söyle.',
  'Bir dakika boyunca hiç konuşma.',
  'En sevdiğin filmi tek cümleyle kötüle.',
  'Çocukken ne olmak istediğini söyle.',
  'Sana en çok benzeyen kişiyi seç, nedenini anlat.',
  'Bir kişi seç; o kişi sana istediği soruyu sorsun.',
  'En çok mesajlaştığın kişiyi söyle.',
  'Bir anını abartarak anlat, masadakiler abartıyı bulsun.',
  'Sıradaki turda kimin çevireceğini sen seç.',
  'Masaya bir kural koy, bu tur boyunca geçerli olsun.',
  'En utanç verici müzik zevkini itiraf et.',
  'Kadeh kaldır: masadaki birine teşekkür et.',
  'Gözlerini kapat, birini işaret et; o kişi bir yudum alsın.',
  'Bugün kimseye söylemediğin bir şeyi söyle.',
  'Masadan birine bir iyilik sözü ver.',
  'En son kimi aradın, neden aradın?',
  'Bir espri yap; kimse gülmezse sen içersin.',
  'Sana en son kim “seni özledim” dedi?',
  'Bir dakikada üç kişiyi güldürmeye çalış.',
  'Masadaki en iyi hikâye anlatıcısını seç, o bir hikâye anlatsın.',
  'Bir yudum al ya da sıradaki soruyu sen sor.',
  'Telefonunun duvar kâğıdını göster.',
  'Masadakilerden birine yeni bir lakap tak.',
  'Bir dakika boyunca herkese “sen” yerine adıyla hitap et.',
];

export const NHIE_SEVIYE = { klasik: 'Klasik', aci: 'Acı biber', hepsi: 'Karışık' };

/** Kullanılmışları atlayarak rastgele bir öğe seçer. → {i, item} */
export function pick(list, kullanilan, rnd = Math.random) {
  const musait = list.map((_, i) => i).filter(i => !kullanilan.includes(i));
  const havuz = musait.length ? musait : list.map((_, i) => i);
  if (!musait.length) kullanilan.length = 0;
  const i = havuz[Math.floor(rnd() * havuz.length)];
  kullanilan.push(i);
  return { i, item: list[i] };
}
